### ISSUE TITLE
strange behavior with Chinese keyboard

### ISSUE THREAD

**Issue by huangjj27** [akahuku/wasavi#153]
when I typed some Chinese in insert mode it seems fine(for example type a phrase "你好”(means hello)
![image](https://cloud.githubusercontent.com/assets/8068443/19445441/d9671cc8-94c6-11e6-8a6b-c3cfd4a4fe19.png)
but when I return to nomal mode, the cursor jumps to where I began typing like this
![image](https://cloud.githubusercontent.com/assets/8068443/19445488/10161486-94c7-11e6-89fc-8a98a0a7beb9.png)

for I not only use wasavi for coding but also for keeping a Chinese dairy, the problem annoyed me for about a month. please fixed it soon!

**Comment by kenkangxgwe** [comment]
This bug doesn't only occur in Chinese, but all CJK languages, when I use Microsoft Input Method (I didn't test other IMEs).

Another symptom of this bug is pressing `left` or `backspace` in the insert mode will resuit in cursor misplacement. And `right` cannot move the cursor back (even escape to normal mode and press `l`).

**Comment by kenkangxgwe** [comment]
Issue #146 also reported the same bug, I hope @akahuku may fix this. Thanks

**Comment by huangjj27** [comment]
check that the bug fix, with the environment of Ubuntu 16.04, sogou IME(fcitx based)
