### ISSUE TITLE
ctrl-c, ctrl-t

### ISSUE THREAD

**Issue by penguina** [akahuku/wasavi#79]
Can I set Ctrl-c as an alternative Esc key as Ctrl-t as alternative tab key?

**Comment by akahuku** [comment]
`:map LHS RHS`
Currently it is not able to assign a key such as `<C-c>`, `<C-t>` to LHS.
It is a bug, so I'd fix it. Thank you.

But if you are Chrome user, `<C-t>` can not still be used
because in Chrome, some fundamental keys for web navigation are reserved by Chrome
and extension can not control there keys.
